baseUrl: 'http://{PRIMARY_SITE_URL}/'
enabled: true
handle: default
hasUrls: true
language: en-US
name: TRG-mockup
primary: true
siteGroup: 54ba0e7e-3335-45d3-9b7d-851897d0a28d # TRG-mockup
sortOrder: 1
