defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6309e113-72fa-4f1c-abbf-40b6807d0948 # News Entry
handle: news
maxAuthors: 1
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  f8dde0cf-bf8a-4f0d-86d3-dbaaf1917ebe: # TRG-mockup
    enabledByDefault: true
    hasUrls: true
    template: news/_entry.twig
    uriFormat: 'news/{slug}'
type: channel
